// Extracted from logimap/index.html inline script
// Global State Management
let globalState = {
    facility1s: new Map(),
    facility2s: new Map(),
    facility3s: new Map(),
    facility4s: new Map(),
    facility5s: new Map(),
    transportRoutes: new Map(),
    nextFacility1Id: 1,
    nextFacility2Id: 1,
    nextFacility3Id: 1,
    nextFacility4Id: 1,
    nextFacility5Id: 1,
    nextTransportId: 1,
    currentLanguage: 'ja'
};
// Translation System
const translations = {
    ja: { 'app-title': '🚛 ロジスティクスマップジェネレーター', 'toggle-theme': '🌙 ダークモード', 'export-image': '📸 画像出力', 'export-csv': '📊 CSV出力', 'facility-1': '施設1', 'facility-2': '施設2', 'facility-3': '施設3', 'facility-4': '施設4', 'facility-5': '施設5', 'add-facility': '+ 追加', 'transport-config': '輸送設定', 'add-transport-route': '+ 輸送追加', 'from-location': '出発地', 'to-location': '到着地', 'select-location': '場所を選択', 'data-management': 'データ管理', 'import-csv': 'CSV インポート', 'select-csv-file': 'CSVファイルを選択', 'download-template': '📋 サンプルテンプレート', 'to-warehouse': '倉庫へ', 'to-destination': '納入先へ', 'facility-name': '施設名', 'location-type': '所在地', 'domestic': '国内', 'overseas': '海外', 'country': '国', 'city': '都市', 'remove': '削除', 'is-warehouse': '倉庫', 'warehouse-type': '倉庫種別', 'general-warehouse': '一般倉庫', 'bonded-warehouse': '保税倉庫', 'operating-entity': '運営主体', 'own-company': 'own', 'other-company': '他社', 'new': '新規', 'temperature-control': '温湿度管理', 'temperature': '温度', 'humidity': '湿度', 'work-content': '作業内容', 'transport-mode': '輸送モード', 'departure': '出発地', 'arrival': '到着地', 'frequency': '頻度', 'package-type': '荷姿', 'volume': '数量', 'truck': 'トラック', 'ship': '海運', 'air': '航空', 'rail': '鉄道', 'transport-operating-entity': '輸送運営主体', 'transport-entity-name': '運営主体名', 'transport-details': '輸送詳細', 'nx-transport': 'own 輸送', 'other-transport': '他社輸送', 'new-transport': '新規', 'custom-transport': 'カスタム', 'custom-entity-name': 'カスタム運営主体名', 'icon': 'アイコン' },
    en: { 'app-title': '🚛 Logistics Map Generator', 'toggle-theme': '🌙 Dark Mode', 'export-image': '📸 Export Image', 'export-csv': '📊 Export CSV', 'facility-1': 'Facility 1', 'facility-2': 'Facility 2', 'facility-3': 'Facility 3', 'facility-4': 'Facility 4', 'facility-5': 'Facility 5', 'add-facility': '+ Add', 'transport-config': 'Transport Config', 'add-transport-route': '+ Add Route', 'from-location': 'From Location', 'to-location': 'To Location', 'select-location': 'Select Location', 'data-management': 'Data Management', 'import-csv': 'CSV Import', 'select-csv-file': 'Select CSV File', 'download-template': '📋 Sample Template', 'to-warehouse': 'To Warehouse', 'to-destination': 'To Destination', 'facility-name': 'Facility Name', 'location-type': 'Location Type', 'domestic': 'Domestic', 'overseas': 'Overseas', 'country': 'Country', 'city': 'City', 'remove': 'Remove', 'is-warehouse': 'Warehouse', 'warehouse-type': 'Warehouse Type', 'general-warehouse': 'General Warehouse', 'bonded-warehouse': 'Bonded Warehouse', 'operating-entity': 'Operating Entity', 'own-company': 'by own', 'other-company': 'Other Company', 'new': 'New', 'temperature-control': 'Temperature Control', 'temperature': 'Temperature', 'humidity': 'Humidity', 'work-content': 'Work Content', 'transport-mode': 'Transport Mode', 'departure': 'Departure', 'arrival': 'Arrival', 'frequency': 'Frequency', 'package-type': 'Package Type', 'volume': 'Volume', 'truck': 'Truck', 'ship': 'Ship', 'air': 'Air', 'rail': 'Rail', 'transport-operating-entity': 'Transport Entity', 'transport-entity-name': 'Entity Name', 'transport-details': 'Transport Details', 'nx-transport': 'own Transport', 'other-transport': 'Other Transport', 'new-transport': 'New', 'custom-transport': 'Custom', 'custom-entity-name': 'Custom Entity Name', 'icon': 'Icon' },
    zh: { 'app-title': '🚛 物流地图生成器', 'toggle-theme': '🌙 深色模式', 'export-image': '📸 导出图片', 'export-csv': '📊 导出CSV', 'facility-1': '设施1', 'facility-2': '设施2', 'facility-3': '设施3', 'facility-4': '设施4', 'facility-5': '设施5', 'add-facility': '+ 添加', 'transport-config': '运输配置', 'add-transport-route': '+ 添加路线', 'from-location': '出发地', 'to-location': '目的地', 'select-location': '选择地点', 'data-management': '数据管理', 'import-csv': 'CSV导入', 'select-csv-file': '选择CSV文件', 'download-template': '📋 示例模板', 'to-warehouse': '到仓库', 'to-destination': '到目的地', 'facility-name': '设施名称', 'location-type': '位置类型', 'domestic': '国内', 'overseas': '海外', 'country': '国家', 'city': '城市', 'remove': '删除', 'is-warehouse': '仓库', 'warehouse-type': '仓库类型', 'general-warehouse': '普通仓库', 'bonded-warehouse': '保税仓库', 'operating-entity': '运营主体', 'own-company': 'by own', 'other-company': '他营', 'new': '新建', 'temperature-control': '温湿度控制', 'temperature': '温度', 'humidity': '湿度', 'work-content': '工作内容', 'transport-mode': '运输方式', 'departure': '出发地', 'arrival': '到达地', 'frequency': '频率', 'package-type': '包装类型', 'volume': '数量', 'truck': '卡车', 'ship': '船运', 'air': '航空', 'rail': '铁路', 'transport-operating-entity': '运输主体', 'transport-entity-name': '主体名称', 'transport-details': '运输详情', 'nx-transport': 'own 运输', 'other-transport': '其他运输', 'new-transport': '新建', 'custom-transport': '自定义', 'custom-entity-name': '自定义主体名称', 'icon': '图标' }
};
// The rest of the JS is identical to the inline script. For brevity here, paste the contents from lines 1031 to 2500 of the original inline script.